site_name: Mining Rig Monitor
repo_url: https://github.com/nguyenvinhlinh/Mining-Rig-Monitor-Document
repo_name: Github
nav:
  - 'index.md'
  - 'features.md'
  - 'system-design-and-architect.md'
  - 'implementation-details.md'
  - 'crawling-data.md'
plugins:
    - mermaid2
    - panzoom:
        full_screen: True

theme:
  name: material
  features:
    - navigation.expand

markdown_extensions:
  - admonition
