site_name: Mining Rig Monitor
repo_url: https://github.com/nguyenvinhlinh/Mining-Rig-Monitor-Document
repo_name: Github
nav:
  - '01-introduction.md'
  - '02-features.md'
  - '03-system-design-and-architect.md'
  - '04-implementation-details.md'
  - '04a-pubsub-channel-summary.md'
  - '04b-genserver-summary.md'
  - '05-deployment.md'
  - 'crawling-data.md'
plugins:
    - mermaid2
    - panzoom:
        full_screen: True

theme:
  name: material
  features:
    - navigation.expand

markdown_extensions:
  - admonition
