site_name: Mining Rig Monitor
site_author: Nguyen Vinh Linh

repo_url: https://github.com/nguyenvinhlinh/Mining-Rig-Monitor-Document
repo_name: nguyenvinhlinh/Mining-Rig-Monitor-Document

copyright: Copyright &copy; 2024 - 2025 Nguyen Vinh Linh

nav:
  - '01-introduction.md'
  - '02-features.md'
  - '03-system-design-and-architect.md'
  - '4. Implementation Details':
      - '4.1 ERD & DB diagrams': '04.1-erd-db-diagram.md'
      - '4.2 Pubsub channel summary':  '042-pubsub-channel-summary.md'
      - '4.3 Genserver Summary': '043-genserver-summary.md'
      - '4.4 CPU/GPU related features': '044-cpu-gpu-related-features.md'
      - '4.5 ASIC related features': '045-asic-related-features.md'
  - '05-deployment.md'
  - '06-project-management.md'
  - 'crawling-data.md'

plugins:
    - mermaid2
    - panzoom:
        full_screen: True
    - search

theme:
  name: material
  features:
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition

extra_css:
  - style.css
