site_name: Mining Rig Monitor
site_author: Nguyen Vinh Linh

repo_url: https://github.com/nguyenvinhlinh/Mining-Rig-Monitor-Document
repo_name: nguyenvinhlinh/Mining-Rig-Monitor-Document

copyright: Copyright &copy; 2024 - 2025 Nguyen Vinh Linh

nav:
  - '01-introduction.md'
  - '02-features.md'
  - '03-system-design-and-architect.md'

  - '4. Mining Rig Monitor':
      - '4.1 ERD & DB diagrams': '04.01-erd-db-diagram.md'
      - '4.2 Pubsub channel summary':  '04.02-pubsub-channel-summary.md'
      - '4.3 Genserver Summary': '04.03-genserver-summary.md'
      - '4.4 CPU/GPU related features': '04.04-cpu-gpu-related-features.md'
      - '4.5 ASIC related features': '04.05-asic-related-features.md'
      - '4.6 Release Commands': '04.06-release-commands.md'
      - '4.7 How-To':
          - '04.08-how-to-release-manually.md'
          - '04.09-How-to-deploy-manully.md'
          - '04.10-where-are-file-installed.md'
          - '04.11-How-to-deploy-with-rpm.md'
          - '04.12-How-to-use-nginx-as-reverse-proxy.md'
          - '04.13-How-to-make-rpm-package.md'

  - '5. ASIC Sentry':
      - '5.1 Introduction': '05.01-introduction.md'
      - '5.2 Database Diagram': '05.02-asic-sentry-db.md'
      - '5.3 How-To':
          - 'How to make release?': '05.03.01-How-to-release-manually.md'
          - 'How to deploy manually?': '05.03.02-How-to-deploy-manually.md'
          - 'How to configure api_url?': '05.03.03-How-to-find-mininig_rig_commander_api_url.md'
          - 'Where are file installed?': '05.03.03-Where-are-file-installed.md'
          - '05.03.01-How-to-make-rpm-package.md'
      - 'crawling-data.md'
  - '6. Project Management': '06-project-management.md'


plugins:
    - mermaid2
    - panzoom:
        full_screen: True
    - search

theme:
  name: material
  features:
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list

extra_css:
  - style.css
