site_name: Mining Rig Monitor
site_author: Nguyen Vinh Linh

repo_url: https://github.com/nguyenvinhlinh/Mining-Rig-Monitor-Document
repo_name: nguyenvinhlinh/Mining-Rig-Monitor-Document

copyright: Copyright &copy; 2024 - 2025 Nguyen Vinh Linh

nav:
  - '01-introduction.md'
  - '02-features.md'
  - '03-system-design-and-architect.md'

  - '4. Mining Rig Monitor':
      - '4.1 ERD & DB diagrams': '04.01-erd-db-diagram.md'
      - '4.2 Pubsub channel summary':  '04.02-pubsub-channel-summary.md'
      - '4.3 Genserver Summary': '04.03-genserver-summary.md'
      - '4.4 CPU/GPU related features': '04.04-cpu-gpu-related-features.md'
      - '4.5 ASIC related features': '04.05-asic-related-features.md'
      - '4.6 Release Commands': '04.06-release-commands.md'
      - '4.7 How-To':
          - '04.07.01-how-to-release-manually.md'
          - '04.07.02-How-to-deploy-manully.md'
          - '04.07.03-where-are-file-installed.md'
          - '04.07.04-How-to-deploy-with-rpm.md'
          - '04.07.05-How-to-use-nginx-as-reverse-proxy.md'
          - '04.07.06-How-to-make-rpm-package.md'
      - '4.8 HTML Templates': '04.08-html-templates.md'


  - '5. ASIC Sentry':
      - '5.1 Introduction': '05.01-introduction.md'
      - '5.2 Database Diagram': '05.02-asic-sentry-db.md'
      - '5.3 How-To':
          - 'How to make release?': '05.03.01-How-to-release-manually.md'
          - 'How to deploy manually?': '05.03.02-How-to-deploy-manually.md'
          - 'How to deploy with rpm?' : '05.03.04-How-to-deploy-with-rpm.md'
          - 'How to configure api_url?': '05.03.03-How-to-find-mininig_rig_commander_api_url.md'
          - 'Where are file installed?': '05.03.03-Where-are-file-installed.md'
          - 'How to setup basic auth & ssl with NGINX': '05.03.05-How-to-setup-basic-auth-ssl.md'
          - '05.03.01-How-to-make-rpm-package.md'
      - 'crawling-data.md'
  - '6. CPU/GPU Sentry':
      - '6.1 Features':
          - '6.1.0 Feature List': '06.01.00-cpu-gpu-sentry-feature-list.md'
          - '6.1.1 Fetching new playbook': '06.01.01-feature-regular-fetching-mining-playbooks.md'
      - '6.2 Architecture':
          - '6.2.1 GenServer Summary': '06.02.01-Genserver-summary.md'
      - '6.3 How-To':
          - '6.3.1 How to make release?': '06.03.01-how-to-make-release.md'
          - '6.3.2 How to deploy manually?': '06.03.02-How-to-deploy-manually.md'
  - '7. Remote Relay Controller':
      - '7.1 Introduction': '07.01-introduction.md'
      - '7.2 Features':
          - '7.2.1 Turn On/Off ASIC Miner': '07.02.01-Turn-on-off-asic-miner.md'


  - '8. Project Management':
      '2024-12-26 to 2025-04-12': '08.01-project-management.md'
      '2025-05-07 to futurre': '08.02-project-management.md'



plugins:
    - mermaid2
    - panzoom:
        full_screen: True
    - search

theme:
  name: material
  features:
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
extra_css:
  - style.css
